### ISSUE TITLE
Cuadro comparativo 

### ISSUE THREAD

**Issue by MarleneRamirez0731** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-MarleneRamirez0731#1]
Marlene Maricela Osorio Ramírez 

![png_20221003_114723_0000](https://user-images.githubusercontent.com/112357070/193633439-e8eb613d-4c5d-4565-a2ce-722b1b3fc0f9.png)

**Comment by AmeliReyesHernandez** [comment]
Corregir

**Comment by MarleneRamirez0731** [comment]
![1_20221003_155832_0000](https://user-images.githubusercontent.com/112357070/193681330-86a816ad-430c-429a-a9e0-1589cb08feab.png)
![2_20221003_155832_0001](https://user-images.githubusercontent.com/112357070/193681339-1e419969-0904-4e5e-9e77-d385d4054f3a.png)

**Comment by AmeliReyesHernandez** [comment]
19.6 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
